// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/chart": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "image/png"
                ],
                "summary": "Генерация графика",
                "parameters": [
                    {
                        "type": "number",
                        "description": "X0",
                        "name": "X0",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "Y0",
                        "name": "Y0",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "A",
                        "name": "A",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "B",
                        "name": "B",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "E",
                        "name": "E",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "description": "D",
                        "name": "D",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Генерируемый график",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Хищник-Жертва",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
